# This file is used by Bundler to manage fastlane dependencies.
# To install fastlane, run `gem install fastlane` or `bundle install` in this directory.

source "https://rubygems.org"

# Install fastlane
gem "fastlane"

# Install CocoaPods for iOS builds
# Exclude problematic versions that cause build failures
gem "cocoapods", ">= 1.13", "!= 1.15.0", "!= 1.15.1"
gem "activesupport", ">= 6.1.7.5", "!= 7.1.0"
gem "xcodeproj", "< 1.26.0"
gem "concurrent-ruby", "< 1.3.4"

# Ruby 3.4.0 has removed some libraries from the standard library
gem "bigdecimal"
gem "logger"
gem "benchmark"
gem "mutex_m"

# If you use any plugins, add them here
# For example: gem "fastlane-plugin-flutter", "~> 0.1.0"
